# Generated by Django 4.1.6 on 2023-03-24 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votant',
            unique_together={('votant', 'idee')},
        ),
    ]
